const employeesData = [
  {
    name: "Ethan Carter",
    email: "ethan.carter@example.com",
    password: "123",
    type: "Employee",
    tasks: [
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Build Responsive Navbar",
        taskDescription:
          "Create a mobile-friendly navbar using Flexbox and media queries.",
        category: "UI Development",
        date: "2025-05-26",
      },
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Dark Mode Toggle",
        taskDescription:
          "Implement theme switching using CSS variables and JavaScript.",
        category: "Feature Enhancement",
        date: "2025-05-27",
      },
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Sticky Header",
        taskDescription: "Make the header stick to the top on scroll.",
        category: "UX Improvement",
        date: "2025-05-28",
      },
    ],
  },
  {
    name: "Liam Bennett",
    email: "liam.bennett@example.com",
    password: "456",
    type: "Employee",
    tasks: [
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Landing Page Layout",
        taskDescription:
          "Design the landing page layout using Tailwind utility classes.",
        category: "Layout Design",
        date: "2025-05-26",
      },
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Hero Section Animation",
        taskDescription:
          "Add Framer Motion-based animation to the hero content.",
        category: "Animation",
        date: "2025-05-26",
      },
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Call to Action Design",
        taskDescription:
          "Create a responsive CTA section with gradient background.",
        category: "Design",
        date: "2025-05-30",
      },
    ],
  },
  {
    name: "Noah Harrison",
    email: "noah.harrison@example.com",
    password: "789",
    type: "Employee",
    tasks: [
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "React Form Validation",
        taskDescription:
          "Validate form using React Hook Form + Yup integration.",
        category: "Form Handling",
        date: "2025-05-30",
      },
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Toast Notification Setup",
        taskDescription: "Use React Toastify for success/error messages.",
        category: "UX Enhancement",
        date: "2025-05-30",
      },
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Form Submission Loader",
        taskDescription: "Add loading spinner on form submission.",
        category: "User Feedback",
        date: "2025-05-31",
      },
    ],
  },
  {
    name: "Lucas Mitchell",
    email: "lucas.mitchell@example.com",
    password: "111",
    type: "Employee",
    tasks: [
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Implement Routing",
        taskDescription: "Configure multiple pages using React Router DOM.",
        category: "Routing",
        date: "2025-05-30",
      },
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Lazy Load Components",
        taskDescription: "Use React.lazy and Suspense to lazy-load routes.",
        category: "Performance",
        date: "2025-05-30",
      },
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "404 Page Design",
        taskDescription: "Create a custom 404 Not Found page with back button.",
        category: "UI Design",
        date: "2025-05-30",
      },
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Redirect Auth Users",
        taskDescription: "Redirect users to dashboard if already logged in.",
        category: "Authentication",
        date: "2025-05-31",
      },
    ],
  },
  {
    name: "Olivia Morgan",
    email: "olivia.morgan@example.com",
    password: "222",
    type: "Employee",
    tasks: [
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Fix Cross-Browser Issues",
        taskDescription:
          "Ensure consistent design across Chrome, Firefox, and Safari.",
        category: "Browser Compatibility",
        date: "2025-05-30",
      },
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "SEO Optimization",
        taskDescription:
          "Add proper meta tags and alt attributes for SEO boost.",
        category: "SEO",
        date: "2025-05-31",
      },
      {
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
        taskTitle: "Accessibility Improvements",
        taskDescription: "Ensure proper ARIA roles and keyboard navigation.",
        category: "Accessibility",
        date: "2025-05-31",
      },
    ],
  },
];

module.exports = { data: employeesData };
